// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_name_ from "./routes/[name].tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $education from "./routes/education.tsx";
import * as $experience from "./routes/experience.tsx";
import * as $index from "./routes/index.tsx";
import * as $portfolio_layout from "./routes/portfolio/_layout.tsx";
import * as $portfolio_graphic_design from "./routes/portfolio/graphic-design.tsx";
import * as $portfolio_ux_design_mediq from "./routes/portfolio/ux-design-mediq.tsx";
import * as $skills from "./routes/skills.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $_name_,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/education.tsx": $education,
    "./routes/experience.tsx": $experience,
    "./routes/index.tsx": $index,
    "./routes/portfolio/_layout.tsx": $portfolio_layout,
    "./routes/portfolio/graphic-design.tsx": $portfolio_graphic_design,
    "./routes/portfolio/ux-design-mediq.tsx": $portfolio_ux_design_mediq,
    "./routes/skills.tsx": $skills,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
